CREATE TABLE IF NOT EXISTS `movie` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `englishTitle` VARCHAR(255) DEFAULT NULL,
  `year` SMALLINT UNSIGNED DEFAULT NULL,
  `quality` VARCHAR(30) DEFAULT NULL,
  `rating` DECIMAL(3, 1) DEFAULT NULL,
  `episodes` VARCHAR(100) DEFAULT NULL,
  `genre` TEXT DEFAULT NULL,
  `studio` VARCHAR(255) DEFAULT NULL,
  `director` VARCHAR(255) DEFAULT NULL,
  `cast` TEXT DEFAULT NULL,
  `description` TEXT DEFAULT NULL,
  `country` VARCHAR(100) DEFAULT NULL,
  `posterUrl` TEXT DEFAULT NULL,
  `bannerUrl` TEXT DEFAULT NULL,
  `videoUrl` TEXT DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
